---
title: Personalized MathCheck-example
max_points: 2
instructions: |

# acceptPost tuottaa tekstikentän sivulle
# tiedoston palautuslomakkeen sijaan
view_type: access.types.stdasync.acceptPost

fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: ratkaisu # Lomakkeen nimi verkkosivulla
    title: Ratkaisu # Näkyy syötekentän yläpuolella
    required: True

personalized: True

# Luotuja tiedostoja voi olla useampiakin.
generated_files:
  - file: teacher-input.txt
    key: teacher-input
    content_in_template: False
    # Allows the student to
    # download this generated file
    # through a link
    url_in_template: False
    # Allows the student
    # to download the generated file
    allow_download: False

  - file: A
    key: A
    content_in_template: True
    # Allows the student to
    # download this generated file
    # through a link
    url_in_template: False
    # Allows the stundet
    # to download the generated file
    allow_download: False

  - file: B
    key: B
    content_in_template: True
    # Allows the student to
    # download this generated file
    # through a link
    url_in_template: False
    # Allows the stundet
    # to download the generated file
    allow_download: False

  - file: C
    key: C
    content_in_template: True
    # Allows the student to
    # download this generated file
    # through a link
    url_in_template: False
    # Allows the stundet
    # to download the generated file
    allow_download: False

generator:
  cmd: [ "python3", "generator.py" ]
  cwd: exercises/personalized-mathcheck-example/
max_submissions_before_regeneration: 3

# configuration for the new Docker container grading sandbox
container:
  image: sesodesa/grade-mathcheck:2019-07-13
  mount: exercises/personalized-mathcheck-example
  cmd: /exercise/run.sh
